apiVersion: v1
kind: Pod
metadata:
  name: spammer
  namespace: default
spec:
  containers:
  - name: spammer
    image: appropriate/curl
    command: ["/bin/sh", "-c"]
    args:
      - while true; do curl -s http://webserver-service.default.svc.cluster.local; done;