apiVersion: v1
kind: Pod
metadata:
  name: spammer
  namespace: default
spec:
  containers:
  - name: spammer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do wget -O - http://webserver-service.default.svc.cluster.local; done;